services:
    capdigital_ntlm_soap_client:
        class: Capdigital\NtlmSoapClient\Service\CapdigitalNtlmSoapClient
        arguments:
            - "%capdigital_ntlm_soap_client%"

    Capdigital\NtlmSoapClient\Service\CapdigitalNtlmSoapClient:
        alias: 'capdigital_ntlm_soap_client'